#!/bin/sh

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

#######################################################################
# Begin real processing

copy_exec /lib/systemd/systemd-cryptsetup /lib/systemd
copy_exec /lib/x86_64-linux-gnu/cryptsetup/libcryptsetup-token-systemd-tpm2.so /lib/x86_64-linux-gnu/cryptsetup/libcryptsetup-token-systemd-tpm2.so
for i in /lib/x86_64-linux-gnu/libtss2*
do
	copy_exec ${i} /lib/x86_64-linux-gnu
done
